default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: pguser
  password: password

development:
  <<: *default
  database: Sample_App_Ruby_development

test:
  <<: *default
  database: Sample_App_Ruby_test

production:
  <<: *default
  database: Sample_App_Ruby_production
  username: Sample_App_Ruby
  password: <%= ENV['Sample_App_Ruby_DATABASE_PASSWORD'] %>
