users:
 max_name_length: 50
 max_email_length: 255
 password_min_length: 6
<<<<<<< HEAD
=======
 email_regex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
>>>>>>> b26ad6c (Add gem config)
 email_uniqueness: true